---
- name: Update Ubuntu servers
  hosts: ubuntu
  become: yes

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display reboot required message
      debug:
        msg: "Reboot is required for {{ inventory_hostname }}"
      when: reboot_required.stat.exists
